# Generated by Django 6.1.1 on 2026-09-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='relation',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('FRIEND', 'Friend'), ('RELATIVE', 'Relative'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
