# Generated by Django 6.1.1 on 2026-09-17 05:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_studentprofile'),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_date', models.DateField(default=django.utils.timezone.now)),
                ('vacated_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('VACATED', 'Vacated')], default='ACTIVE', max_length=10)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.bed')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounts.studentprofile')),
            ],
        ),
    ]
